### ISSUE TITLE
Does not work anymore.

### ISSUE THREAD

**Issue by theodrim** [seligman/dir_sizer#2]
Hello, thank you for an awesome project. It was working for me quite fine few months ago, but tested yesterday and received following stack trace:

```
Scanning...Traceback (most recent call last):
  File "/Users/alexk/src/dir_sizer/dir_sizer.py", line 264, in <module>
    main()
  File "/Users/alexk/src/dir_sizer/dir_sizer.py", line 190, in main
    for filename, size in load_files(opts, abstraction):
  File "/Users/alexk/src/dir_sizer/dir_sizer.py", line 256, in load_files
    for filename, size in abstraction.scan_folder(opts):
  File "/Users/alexk/src/dir_sizer/s3_abstraction.py", line 313, in scan_folder
    for i, cur in enumerate(s3_list_objects(msg, opts, s3)):
  File "/Users/alexk/src/dir_sizer/s3_abstraction.py", line 272, in s3_list_objects
    for row in get_bucket_inventory(msg, s3, opts['s3_bucket'], required_fields=required_fields, prefix=prefix):
  File "/Users/alexk/src/dir_sizer/s3_abstraction.py", line 206, in get_bucket_inventory
    inv_prefix = config['Destination']['S3BucketDestination']['Prefix']
KeyError: 'Prefix'

```

Environment: Python 3.9.13, macos, fresh virtual env with `boto3` and `Pillow` installed.
Inventory file: [94990aad-1014-4013-809c-82a266e40f14.csv.gz](https://github.com/seligman/dir_sizer/files/9930805/94990aad-1014-4013-809c-82a266e40f14.csv.gz)
s3 inventory config: 
![image](https://user-images.githubusercontent.com/65532444/199770569-39c7b159-ea16-421e-875f-717fe0bee870.png)

I've additionally tested inside fresh linux vm, as well as docker container (with minimal dockerfile), but got same error.

Should I still define default prefix for scanning ?
Please let me know if I should provide any additional information, and once again thanks for the help and awesome tool!

**Comment by seligman** [comment]
Thanks for the detailed report!

Can you try the latest version that pulls in a3984a57b5c5ede96cca9f66d702f27b92fe4df3 ? It should fix this issue.

**Comment by seligman** [comment]
Closing due to lack of feedback.

If you're still running into this issue, please feel free to reopen it.

**Comment by theodrim** [comment]
Hello, sorry for not coming back sooner - hectic week that was. It's working fine now after pulling in https://github.com/seligman/dir_sizer/commit/a3984a57b5c5ede96cca9f66d702f27b92fe4df3 - thank you.
